<?php

namespace tests\PluginRekap\Libraries;

use PHPUnit_Framework_TestCase;
use PluginRekap\Libraries\Formatter;
use PluginRekap\Libraries\Segments;

class FormatterTest extends PHPUnit_Framework_TestCase{

    /**
     * @var Formatter
     */
    private $formatter;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->formatter = new Formatter(new Segments());
    }

    public function test_format(){
        $this->assertEquals(array (
            0 => '1234|2',
            1 => '234|7',
            2 => '34|6',
        ), $this->formatter->format('1234x2.7.6'));

        $this->assertEquals(array (
            0 => '1234|2',
            1 => '234|7',
        ), $this->formatter->format('1234x2.7'));

        $this->assertEquals(array (
            0 => '1234|9',
        ), $this->formatter->format('1234x9'));

        $this->assertEquals(array (
            0 => '123|9',
            1 => '23|5',
        ), $this->formatter->format('123x9.5'));
    }


}